<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="PdfPig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lumen.Domain\Lumen.Domain.csproj" />
  </ItemGroup>

</Project>
